config/routes.rb
Rails.application.routes.draw do
  root 'homes#top'
  resources :books
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
  
  validates :title, presence: true
  validates :body, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  def index
    @books = Book.all
    @book = Book.new
  end

  def create
    @books = Book.all
    @book = Book.new(book_params)
    if @book.save
      flash[:notice] = "book was successfully created."
      redirect_to "/books/#{@book.id}"
    else
      render :index
    end
  end

  def show
    @book = Book.find(params[:id])
  end

  def edit
    @book = Book.find(params[:id])
  end

  def update
    @book = Book.find(params[:id])
    if @book.update(book_params)
      flash[:notice] = "book was successfully updated."
      redirect_to book_path(@book.id)
    else
      render :edit
    end
  end

  def destroy
    book = Book.find(params[:id])
    book.destroy
    redirect_to "/books"
  end

  private
  def book_params
    params.require(:book).permit(:title,:body)
  end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/views/books/edit.html.erb
<div style = "margin-left: 30px;">
  <% if @book.errors.any? %>
  <!--エラーの数表示-->
    <% if (@book.errors.count == 1) %>
      <%= @book.errors.count %>error
    <% else %>
      <%= @book.errors.count %>errors
    <% end %>
    <!--エラーの内容の表示-->
    <ul>
    <% @book.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
    </ul>
  <% end %>
</div>

<div style = "margin-left: 30px;">
  <h2>Editing Book</h2>

  <%= form_with model: @book do |f| %>
    Title<br>
    <%= f.text_field :title %>
    <br>
    <br>
    Body<br>
    <%= f.text_area :body %>
    <br>
    <%= f.submit 'Update Book' %>
  <% end %>
  </div>

<div style = "margin-left: 30px;">
  <%= link_to "show", "/books/#{@book.id}" %>
  <%= link_to "back", "/books" %>

</div>

app/views/books/index.html.erb
<body>

  <div style = "margin-left: 30px;">
    <h2>Books</h2>
  <table>
    <tr>
      <th>Title</th>
      <th>body</th>
    </tr>
    <% @books.each do |book| %>
      <tr>
        <td><%=book.title %></td>
        <td><%=book.body %></td>
        <td><%= link_to "Show", "/books/#{book.id}" %></td>
        <td><%= link_to "Edit", "/books/#{book.id}/edit" %></td>
        <td><%= link_to "Destroy", "/books/#{book.id}", method: :delete, "data-confirm" => "Are you sure?" %></td>
      </tr>
    <% end %>
  </table>
  </div>
  
  <!--エラー表示-->
  <div style = "margin-left: 30px;">
    <% if @book.errors.any? %>
      <!--エラーの数表示-->
      <% if (@book.errors.count == 1) %>
        <%= @book.errors.count %>error
      <% else %>
        <%= @book.errors.count %>errors
      <% end %>
      <!--エラーの内容の表示-->
      <ul>
      <% @book.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
      <% end %>
  </div>
    
  <div style = "margin-left: 30px;">
    <h2>New book</h2>
  <%= form_with model: Book.new do |f| %>
    Title<br>
    <%= f.text_field :title %>
    <br>
    <br>
    Body<br>
    <%= f.text_area :body %>
    <br>

    <%= f.submit 'Create Book' %>
  <% end %>
  </div>
</body>

app/views/books/show.html.erb
<br>
<div style = "margin-left: 100px;">
<%= flash[:notice] %>
</div>
  
<div style = "margin-left: 70px;">
  <b>Title:</b>
  <%= @book.title %><br>
  <br>

  <b>Body:</b>
  <%= @book.body %><br>
  <br>
</div>

<div style = "margin-left: 30px;">
  <%= link_to "Edit", "/books/#{@book.id}/edit" %>
   |
  <%= link_to "Back", "/books" %>

</div>

app/views/homes/top.html.erb
<div style = "margin-left: 30px;">
  <h1>ようこそ Bookersへ！</h1>
</div>

<div style = "margin-left: 70px;">
  <p><b>Bookers</b>では様々な書籍に関するあなたの意見や<br>印象を共有し交換することができます<br></p>
<%= link_to "start", books_path %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookers</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>